### PR TITLE
Introduce C-l to strip dir-components, and fix scroll

### LINKED ISSUE #42: Unable to work with in dev mode
dev mode throws this error:

  Cannot find module 'atom-space-pen-views'

I know the module is deprecated, but how is it working in normal mode?

### PR DESCRIPTION
**Pull request by artagnon**
I can't test this: feel free to either modify and commit, or help me fix #42.

Thanks.

### CODE REVIEW

**Comment by artagnon** [comment]
Fixed. Works now, please pull if happy.

**Comment by Osmose** [comment]
Cool, thanks for the PR!

I'll try to take a look at this soon, sometime this weekend at the latest.

**Comment by artagnon** [comment]
I just made another update to it. Should be perfect now.

File: lib/advanced-open-file-view.coffee [hunk 1]
```diff
@@ -244,6 +245,7 @@ class AdvancedFileView extends View
       newPath = ''
 
     @miniEditor.setText(newPath)
+    @miniEditor.getModel().scrollToCursorPosition()
```
Comment (Osmose) [inline lib/advanced-open-file-view.coffee]: Neato, never heard of this method before! Much easier than the old scroll hack thing I used before, I decided to [replace it](https://github.com/Osmose/advanced-open-file/commit/6fdd867f509aaf68acbd23617558eddfa83d8875).

File: lib/advanced-open-file-view.coffee [hunk 2]
```diff
@@ -323,8 +325,15 @@ class AdvancedFileView extends View
   undo: ->
     if @pathHistory.length > 0
       @miniEditor.setText @pathHistory.pop()
-    else
```
Comment (Osmose) [inline lib/advanced-open-file-view.coffee]: Don't want to remove this beep when the undo queue is empty.

File: lib/advanced-open-file-view.coffee [hunk 3]
```diff
@@ -323,8 +325,15 @@ class AdvancedFileView extends View
...
-      atom.beep()
+      @miniEditor.getModel().scrollToCursorPosition()
+
+  deleteComponent: ->
+    fullPath = @miniEditor.getText()
+    if (fullPath[fullPath.length - 1] == "/")
+      fullPath = fullPath[0..-2]
+    lastSlash = fullPath.lastIndexOf("/")
+    @miniEditor.setText fullPath[0..lastSlash]
```
Comment (Osmose) [inline lib/advanced-open-file-view.coffee]: I think you could simplify this by using `path.dirname` and appending a slash to the result.

Comment (Osmose) [inline lib/advanced-open-file-view.coffee]: Also, you'll want to use `updatePath` here, which adds the old path to the undo history, and removes the need to call `scrollToCursorPosition`.

File: lib/advanced-open-file-view.coffee [hunk 4]
```diff
@@ -411,6 +420,7 @@ class AdvancedFileView extends View
           suggestedPath = projectPaths[0] + path.sep
 
     @miniEditor.setText suggestedPath
+    @miniEditor.getModel().scrollToCursorPosition()
```
Comment (Osmose) [inline lib/advanced-open-file-view.coffee]: Since `attach` is the only method that calls this, and since `attach` does this scrolling later on anyway, this is unnecessary.

File: lib/advanced-open-file-view.coffee [hunk 5]
```diff
@@ -323,8 +325,15 @@ class AdvancedFileView extends View
   undo: ->
     if @pathHistory.length > 0
       @miniEditor.setText @pathHistory.pop()
-    else
-      atom.beep()
+      @miniEditor.getModel().scrollToCursorPosition()
```
Comment (Osmose) [inline lib/advanced-open-file-view.coffee]: Good idea to scroll to the cursor after an undo! That's standard behavior that we're missing.

File: lib/advanced-open-file-view.coffee (hunk 1 above)
Comment (Osmose) [inline lib/advanced-open-file-view.coffee]: Speaking of which, with that commit you can just call `@scrollToCursor()` here and in `undo` instead of calling it directly.

File: keymaps/advanced-open-file.cson [hunk 6]
```diff
@@ -27,6 +27,7 @@
   'ctrl-k': 'advanced-open-file:move-cursor-down'
 
 '.platform-darwin .advanced-open-file atom-text-editor':
+  'ctrl-l': 'advanced-open-file:delete-a-path-component'
```
Comment (Osmose) [inline keymaps/advanced-open-file.cson]: This is totally minor, but `delete-path-component` matches the language of the other commands better. Honestly, though, that's just me being nitpicky. :P

File: lib/advanced-open-file-view.coffee [hunk 7]
```diff
@@ -323,8 +325,15 @@ class AdvancedFileView extends View
...
+
+  deleteComponent: ->
```
Comment (Osmose) [inline lib/advanced-open-file-view.coffee]: Maybe name this `deletePathComponent` to be more specific?

**Comment by Osmose** [comment]
This looks pretty good! Tested it locally and it totally works. Nice work!

Let me know when you push up another version and I'd be happy to confirm it's good and merge it in! Afterwards I'll add some docs for the new keybinding and add you to the `CONTRIBUTORS` file. :D

**Comment by artagnon** [comment]
Thanks for the detailed review! I've pushed out a new version; let me know if I've missed something.

**Comment by artagnon** [comment]
Okay, another iteration. This time, I found that confirm-selected-or-first is more useful than the original confirm-selected-or-only (simply amended your commit). Also got around to writing documentation for delete-path-component finally.

Like it?

**Comment by Osmose** [comment]
I'm fine with the change to `confirm-selected-or-first`, but it really belongs in a separate PR from this one. Could you split it off?

(I'll be spending some time on the project tomorrow afternoon so I'll get to reviewing and stuff like that then, thanks for the patience!)

**Comment by Osmose** [comment]
Looks great, nice work! Thanks again for the contribution. :D
